name: CICD - Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      
    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP > ~/.ssh/known_hosts
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: .
          file: client/Dockerfile
          push: true
          tags: nomadicthinking/reactive-resume-client:latest

      - name: Deployment
        run: |
          ssh $SERVER_USER@$SERVER_IP bash /root/deployment.sh $BRANCH_NAME
